# General
SCREEN_WIDTH: int = 1280
SCREEN_HEIGHT: int = 720
LINE_WIDTH: int = 2
TARGET_FPS: int = 60

# Player
PLAYER_RADIUS: float = 20
PLAYER_TURN_SPEED: float = 300
PLAYER_SPEED: float = 200
SHOT_RADIUS: float = 5
PLAYER_SHOT_SPEED: float = 500
PLAYER_SHOOT_COOLDOWN_SECONDS: float = 0.3

# Asteroid
ASTEROID_SIZES: int = 3
ASTEROID_SPAWN_RATE_SECONDS: float = 0.8
ASTEROID_MIN_RADIUS: float = 20
ASTEROID_MAX_RADIUS: float = ASTEROID_MIN_RADIUS * ASTEROID_SIZES
ASTEROID_MIN_SPEED: int = 40
ASTEROID_MAX_SPEED: int = 100
